export default metricRef =  {
    "allPvE": {
        "killsDeathsRatio": "KDR",
        "kills": "Kills",
        "deaths": "Deaths",
        "secondsPlayed": "Hours Played",
        "assists": "Assists",
        "averageLifespan": "Average Lifespan",
        "bestSingleGameKills": "Best Single Game Kills",
        "opponentsDefeated": "Defeats (Kills + Assists)",
        "efficiency": "Efficiency",
        "killsDeathsAssists": "KDA",
        "precisionKills": "Precision Kills",
        "resurrectionsPerformed": "Revives Performed",
        "resurrectionsReceived": "Times Revived",
        "heroicPublicEventsCompleted": "Heroic Public Events Completed",
        "adventuresCompleted": "Adventures Completed",
        "suicides": "Suicides",
        "weaponKillsAutoRifle": "Auto Rifle Kills",
        "weaponKillsFusionRifle": "Fusion Rifle Kills",
        "weaponKillsHandCannon": "Hand Cannon Kills",
        "weaponKillsTraceRifle": "Trace Rifle Kills",
        "weaponKillsPulseRifle": "Pulse Rifle Kills",
        "weaponKillsRocketLauncher": "Rocket Launcher Kills",
        "weaponKillsScoutRifle": "Scout Rifle Kills",
        "weaponKillsShotgun": "Shotgun Kills",
        "weaponKillsSniper": "Sniper Kills",
        "weaponKillsSubmachinegun": "SMG Kills",
        "weaponKillsRelic": "Relic Kills",
        "weaponKillsSideArm": "Sidearm Kills",
        "weaponKillsSword": "Sword Kills",
        "weaponKillsAbility": "Ability Kills",
        "weaponKillsGrenade": "Grenade Kills",
        "weaponKillsGrenadeLauncher": "Grenade Launcher Kills",
        "weaponKillsSuper": "Super Kills",
        "weaponKillsMelee": "Melee Kills",
        "longestKillSpree": "Longest Killing Spree",
        "longestSingleLife": "Longest Life",
        "mostPrecisionKills": "Most Precision Kills",
        "orbsDropped": "Orbs Produced",
        "orbsGathered": "Orbs Gathered",
        "publicEventsCompleted": "Public Events Completed",
    },
    "allPvP": {
        "killsDeathsRatio": "KDR",
        "efficiency": "Efficiency",
        "kills": "Kills",
        "deaths": "Deaths",
        "activitiesWon": "Wins",
        "winLossRatio": "Win/Loss Ratio",
        "combatRating": "Combat Rating",
        "assists": "Assists",
        "secondsPlayed": "Hours Played",
        "averageLifespan": "Average Lifespan",
        "bestSingleGameKills": "Best Single Game Kills",
        "opponentsDefeated": "Defeats (Kills + Assists)",
        "objectivesCompleted": "Objectives Completed",
        "precisionKills": "Precision Kills",
        "resurrectionsPerformed": "Revives Performed",
        "resurrectionsReceived": "Times Revived",
        "suicides": "Suicides",
        "weaponKillsAutoRifle": "Auto Rifle Kills",
        "weaponKillsFusionRifle": "Fusion Rifle Kills",
        "weaponKillsHandCannon": "Hand Cannon Kills",
        "weaponKillsTraceRifle": "Trace Rifle Kills",
        "weaponKillsPulseRifle": "Pulse Rifle Kills",
        "weaponKillsRocketLauncher": "Rocket Launcher Kills",
        "weaponKillsScoutRifle": "Scout Rifle Kills",
        "weaponKillsShotgun": "Shotgun Kills",
        "weaponKillsSniper": "Sniper Kills",
        "weaponKillsSubmachinegun": "SMG Kills",
        "weaponKillsRelic": "Relic Kills",
        "weaponKillsSideArm": "Sidearm Kills",
        "weaponKillsSword": "Sword Kills",
        "weaponKillsAbility": "Ability Kills",
        "weaponKillsGrenade": "Grenade Kills",
        "weaponKillsGrenadeLauncher": "Grenade Launcher Kills",
        "weaponKillsSuper": "Super Kills",
        "weaponKillsMelee": "Melee Kills",
        "longestKillSpree": "Longest Killing Spree",
        "longestSingleLife": "Longest Life",
        "mostPrecisionKills": "Most Precision Kills",
        "orbsDropped": "Orbs Produced",
        "orbsGathered": "Orbs Gathered",
    }
}
        
    